### ISSUE TITLE
fault response contains string value where integer expected

### ISSUE THREAD

**Issue by ngomezleal** [ieski/OdooXmlRpc#17]
Hello, I hope you're very well.
I'm implementing the dll with odoo 14, and in one method i'm receiving exception.

How Can I decode error? I want know really the problem error.
Do I should active some option or add atribute in method?

I using .net core and c#.net

I hope your answers.
Regards,

**Comment by ieski** [comment]
Can you send me an error or watch packages with Fiddler.

**Comment by ngomezleal** [comment]
Hello ieski, this is the error.
HTTP/1.1 500 Internal Server Error
Transfer-Encoding: chunked
Content-Type: text/plain
Server: Microsoft-IIS/10.0
X-Powered-By: ASP.NET
Date: Tue, 30 Mar 2021 21:24:39 GMT

1000
CookComputing.XmlRpc.XmlRpcTypeMismatchException: fault response contains string value where integer expected [fault response : struct mapped to type Fault : member faultCode mapped to type Int32]
   at CookComputing.XmlRpc.XmlRpcSerializer.ParseString(XmlNode node, Type valueType, ParseStack parseStack)
   at CookComputing.XmlRpc.XmlRpcSerializer.ParseValue(XmlNode node, Type valueType, ParseStack parseStack, MappingAction mappingAction, Type& parsedType, Type& parsedArrayType)
   at CookComputing.XmlRpc.XmlRpcSerializer.ParseStruct(XmlNode node, Type valueType, ParseStack parseStack, MappingAction mappingAction)
   at CookComputing.XmlRpc.XmlRpcSerializer.ParseValue(XmlNode node, Type valueType, ParseStack parseStack, MappingAction mappingAction, Type& parsedType, Type& parsedArrayType)
   at CookComputing.XmlRpc.XmlRpcSerializer.ParseValue(XmlNode node, Type valueType, ParseStack parseStack, MappingAction mappingAction)
   at CookComputing.XmlRpc.XmlRpcSerializer.ParseFault(XmlNode faultNode, ParseStack parseStack, MappingAction mappingAction)
   at CookComputing.XmlRpc.XmlRpcSerializer.DeserializeResponse(XmlDocument xdoc, Type returnType)
   at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke(Object clientObj, MethodInfo mi, Object[] parameters)
   at XmlRpcProxyf547bef4-a713-4ce7-90c7-212d32f3413e.search_read(String dbName, Int32 userId, String dbPwd, String model, String method, Object[] filter, Object[] fields, Int32 offset, Int32 limit, String order)
   at Odoo.Concrete.RpcConnection.SearchAndRead(String model, Object[] filter, Object[] fields, Int32 offset, Int32 limit, String order) in C:\Users\ngome\Documents\Proyectos Nelson Gomez\BackEnd Services\demoXmlRpc\OdooXmlRpc\Odoo\Concrete\RpcConnection.cs:line 76
   at Odoo.Concrete.RpcModel.SearchAndRead(Object[] filter, List`1 fieldsResult, Int32 offset, Int32 limit, String order) in C:\Users\ngome\Documents\Proyectos Nelson Gomez\BackEnd Services\demoXmlRpc\OdooXmlRpc\Odoo\Concrete\RpcModel.cs:line 36
   at Odoo.Concrete.RpcContext.Execute(Boolean read, Int32 offset, Int32 limit, String order) in C:\Users\ngome\Documents\Proyectos Nelson Gomez\BackEnd Services\demoXmlRpc\OdooXmlRpc\Odoo\Concrete\RpcContext.cs:line 67
   at apiRaveOportunidades.Engine.Odoo.GetSalesChannel() in C:\Users\ngome\Documents\Proyectos Nelson Gomez\BackEnd Services\backEndOportunidades\apiRaveOportunidades\Engine\Odoo.cs:line 216
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore
34b
.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: */*
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Host: localhost:44326
User-Agent: PostmanRuntime/7.26.10
OdooFlag: 0
Postman-Token: 171d9391-b4dc-4e75-8996-3a5ed51f7996

0

**Comment by ngomezleal** [comment]
Can you help me please?

**Comment by ieski** [comment]
I think you should check your first odoo connection information.

Sample Connection Info:

{
  "OdooConnection": {
    "ServerUrl": "http://127.0.0.1:8069",
    "DbName": "test",
    "DbUser": "admin",
    "DbPassword": "admin",
    "ImmediateLogin": true,
    "ServerCertificateValidation": true
  }
}

**Comment by ngomezleal** [comment]
Hello ieski, yesterday, I checked the Odoo connection information, and this is working.

I was testing with other models as res.partner, crm.stage ....  in others...., ** and these is working

The error exception is, when **I use crm.team**

Can you help me please?
